spring.application.name=podium

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Server port (Render sets this automatically)
server.port=${PORT:8080}

# Logging
logging.level.org.springframework.security=DEBUG

# JWT secret
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
