spring.application.name=podium

spring.data.mongodb.uri=mongodb://localhost:27017/podium
server.port=8080

logging.level.org.springframework.security=DEBUG

# JWT secret (use a strong key and store in environment variable)
jwt.secret=mySecretKeyForJWTGenerationChangeThisInProduction
jwt.expiration=86400000  
# 24 hours in milliseconds


# PostgreSQL Datasource
spring.datasource.url=jdbc:postgresql://localhost:4455/emaildb
spring.datasource.username=postgres
spring.datasource.password=2002
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
