spring.application.name=podium

server.port=${PORT:8080}

logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=${JWT_SECRET:defaultSecret}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Disable DB (IMPORTANT)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
