spring.application.name=podium

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI}

# Server port (Render will inject PORT)
server.port=${PORT:8080}

# Logging
logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# PostgreSQL
spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
