spring.application.name=podium

spring.data.mongodb.uri=mongodb+srv://abhijeett55:87654321@podium.x9devgj.mongodb.net/podium
server.port=8080

logging.level.org.springframework.security=DEBUG


jwt.secret=mySecretKeyForJWTGenerationChangeThisInProduction
jwt.expiration=86400000
